- name: datatype 
  hosts: web 
  become: yes 
  vars:
    Course: "DOcker"
    list1: 
    - docker 
    - kubs 
    dict1:
      trainer: "NNR8"
      course: "NNR10"
    proj: True  
  tasks: 
  - name: datatype 
    ansible.builtin.debug:
      msg: "{{Course}} {{list1}} {{dict1}} {{proj}}"