- name: shell vs cmd
  hosts: localhost
  become: yes
  tasks:
  - name: shell vs cmd
    ansible.builtin.command: "echo 'Hi,this is command module' > /tmp/command.txt"

  - name: shell vs cmd
    ansible.builtin.shell: "echo 'Hi,this is command module' > /tmp/command.txt"

      