- name: install
  hosts: web
  become: yes
  tasks:
  - name: install
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: "nginx",state: latest}
    - {name: "git",state: absent}

      